#import './fragments/pageFragments.gql'

query HOME_QUERY {
  entry(site: "westeroscraft", section: "home") {
    ... on home_home_Entry {
      pageTitle
      pageDescription
      pageImage {
        url
      }
      homePageContent {
        ... on homePageContent_hero_BlockType {
          heading
          subheading
          heroImage {
            url
          }
          footerImage {
            url
          }
        }
        ... on homePageContent_homebar_BlockType {
          children {
            ... on homePageContent_homeBarItem_BlockType {
              heading
              thumbnail {
                url
              }
              singleLink
            }
          }
        }
      }
      pageSlices {
        ...BANNER_FRAGMENT
        ...DESTINATION_SLIDER_FRAGMENT
        ...VIDEO_FRAGMENT
        ...TEXT_FRAGMENT
        ...TWO_COLUMN_VIDEO_FRAGMENT
        ...TWO_COLUMN_TEXT_FRAGMENT
        ...TIMELINE_FRAGMENT
      }
    }
  }
}
