query DESTINATION_QUERY($slug: [String]) {
  destination: entry(site: "westeroscraft", type: "wikiDestination", slug: $slug) {
    title
    ... on wiki_wikiDestination_Entry {
      title
      slug
      copy
      title
      slug
      ... on wiki_wikiDestination_Entry {
        images {
          url
        }
        projectDetails {
          ... on projectDetails_details_BlockType {
            region
            house
            destinationType
            destinationStatus
          }
        }
      }
    }
  }
  wikiNav: nodes(navHandle: "wikiNav", level: 1) {
    title
    url
    type
    element {
      slug
    }
    children {
      title
      url
      type
      element {
        slug
      }
      parent {
        title
      }
    }
  }
}
