query ROOKERY_QUERY {
  entry(site: "westeroscraft", section: "rookery") {
    title
    ... on rookery_rookery_Entry {
      heading
      subheading
      pageTitle
      pageDescription
      pageImage {
        url
      }
      rookeryList {
        ... on rookeryList_rookery_BlockType {
          rookeryUrl
          rookeryTitle
        }
      }
    }
  }
}
