#import './fragments/wikiFragments.gql'

query BLOCK_BOOK_QUERY {
  entry(slug: "block-book") {
    ... on blockBook_blockBook_Entry {
      title
      pageDescription
      pageImage {
        url
      }
      wikiSlices {
        ... on wikiSlices_text_BlockType {
          ...WIKI_TEXT_FRAGMENT
        }
      }
    }
  }
  categories: categories(group: "blocks") {
    title
    slug
    ... on blocks_Category {
      pageImage {
        url
      }
      pageDescription
    }
  }
}

query CATEGORY_QUERY($id: [Int]) {
  entries(section: "block", type: "block", relatedTo: $id) {
    title
    slug
    ... on block_block_Entry {
      parentBlockName
      blockId
      meta
      namespacedId
      blockType
      material
      sound
      blockCategory {
        title
        slug
      }
      textures {
        url
        title
      }
    }
  }
}

query ALL_CATEGORY_PAGES_QUERY {
  entries(section: "block", type: "block") {
    slug
    id
  }
}
