#import './fragments/pageFragments.gql'

query LAUNCHER_QUERY {
  entry(site: "westeroscraft", section: "launcher") {
    title
    ... on launcher_launcher_Entry {
      heading
      pageTitle
      pageDescription
      pageImage {
        url
      }
      pageSlices {
        ...CONTENT_BANNER_FRAGMENT
        ...BANNER_FRAGMENT
        ...DESTINATION_SLIDER_FRAGMENT
        ...VIDEO_FRAGMENT
        ...TEXT_FRAGMENT
        ...TWO_COLUMN_VIDEO_FRAGMENT
        ...TWO_COLUMN_TEXT_FRAGMENT
        ...TIMELINE_FRAGMENT
      }
    }
  }
}
