fragment spacings on spacings_spacing_BlockType {
  marginTop {
    mobile
    tablet
    desktop
    wide
  }
  marginBottom {
    mobile
    tablet
    desktop
    wide
  }
  paddingTop {
    mobile
    tablet
    desktop
    wide
  }
  paddingBottom {
    mobile
    tablet
    desktop
    wide
  }
}

fragment BANNER_FRAGMENT on pageSlices_banner_BlockType {
  typeHandle
  redactor
  buttons {
    ... on buttons_button_BlockType {
      buttonText
      buttonLink
      variant
      buttonType
      download
    }
  }
  spacings {
    ... on spacings_spacing_BlockType {
      ...spacings
    }
  }
}

fragment DESTINATION_SLIDER_FRAGMENT on pageSlices_destinationSlider_BlockType {
  typeHandle
  redactor
  slider {
    ... on slider_slide_BlockType {
      image {
        url
      }
      slideName
      slideLink
      caption
    }
  }
  linkBuilder {
    ... on linkBuilder_additionalLinks_BlockType {
      additionalLink
      customLinkText
      linkType
      download
    }
  }
  spacings {
    ... on spacings_spacing_BlockType {
      ...spacings
    }
  }
}

fragment TWO_COLUMN_TEXT_FRAGMENT on pageSlices_twoColumnText_BlockType {
  typeHandle
  maxWidth
  columnWidths
  children {
    ... on pageSlices_column_BlockType {
      redactor
      buttons {
        ... on buttons_button_BlockType {
          variant
          buttonText
          buttonLink
          buttonType
          download
        }
      }
    }
  }
  spacings {
    ... on spacings_spacing_BlockType {
      ...spacings
    }
  }
}

fragment VIDEO_FRAGMENT on pageSlices_video_BlockType {
  typeHandle
  videoUrl
  maxWidth
  thumbnail {
    url
  }
  spacings {
    ... on spacings_spacing_BlockType {
      ...spacings
    }
  }
}

fragment TEXT_FRAGMENT on pageSlices_text_BlockType {
  typeHandle
  redactor
  spacings {
    ... on spacings_spacing_BlockType {
      ...spacings
    }
  }
}

fragment TWO_COLUMN_VIDEO_FRAGMENT on pageSlices_twoColumnVideo_BlockType {
  typeHandle
  images {
    url
    title
    ... on images_Asset {
      singleLink
    }
  }
  children {
    ... on pageSlices_column_BlockType {
      typeHandle
      redactor
      buttons {
        ... on buttons_button_BlockType {
          variant
          buttonText
          buttonLink
          buttonType
          download
        }
      }
    }
    ... on pageSlices_video_BlockType {
      typeHandle
      maxWidth
      thumbnail {
        url
        title
      }
      videoUrl
    }
  }
  spacings {
    ... on spacings_spacing_BlockType {
      ...spacings
    }
  }
}

fragment CONTENT_BANNER_FRAGMENT on pageSlices_contentBanner_BlockType {
  typeHandle
  redactor
  buttons {
    ... on buttons_button_BlockType {
      buttonType
      buttonText
      buttonLink
      variant
      download
    }
  }
  linkBuilder {
    ... on linkBuilder_additionalLinks_BlockType {
      additionalLink
      customLinkText
      linkType
      download
    }
  }
  spacings {
    ... on spacings_spacing_BlockType {
      ...spacings
    }
  }
}

fragment TIMELINE_FRAGMENT on pageSlices_timeline_BlockType {
  typeHandle
  children {
    ... on pageSlices_timelineElement_BlockType {
      copy
    }
  }
  spacings {
    ... on spacings_spacing_BlockType {
      ...spacings
    }
  }
}
